### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by jo4356** [jo4356/potato_classifier#1]
- [ ] add percentage prediction
- [ ] prediction only works once until refreshing the page
- [ ] layout and instructions
- [ ] loading large image on web takes a long time (could be fixed with layout?)
